import { StyleSheet } from "react-native";
import { palette } from "../theme";

export const agentActivityStyles = StyleSheet.create({
  content: {
    alignSelf: "center",
    gap: 10,
    maxWidth: 1_040,
    padding: 24,
    paddingBottom: 80,
    width: "100%",
  },
  context: { color: palette.textSecondary, fontSize: 13, marginTop: 4 },
  empty: { alignItems: "center", paddingHorizontal: 30, paddingVertical: 80 },
  emptyCopy: {
    color: palette.textSecondary,
    fontSize: 14,
    lineHeight: 21,
    marginTop: 7,
    maxWidth: 430,
    textAlign: "center",
  },
  emptyGlyph: { color: palette.focus, fontSize: 34 },
  emptyTitle: {
    color: palette.textPrimary,
    fontSize: 18,
    fontWeight: "700",
    marginTop: 12,
  },
  error: {
    backgroundColor: palette.dangerGlass,
    bottom: 12,
    color: palette.danger,
    left: 24,
    padding: 10,
    position: "absolute",
    right: 24,
    textAlign: "center",
  },
  failed: { color: palette.danger },
  kind: {
    color: palette.focus,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.7,
  },
  metric: {
    backgroundColor: palette.surface,
    borderColor: palette.line,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    minWidth: 150,
    padding: 18,
  },
  metricLabel: {
    color: palette.textMuted,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 1,
  },
  metricValue: {
    color: palette.textPrimary,
    fontSize: 30,
    fontWeight: "700",
    marginBottom: 6,
  },
  overview: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    marginBottom: 10,
  },
  pressed: { opacity: 0.55 },
  refresh: {
    alignItems: "center",
    backgroundColor: palette.navigationControl,
    borderColor: palette.glassLine,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  refreshGlyph: { color: palette.focus, fontSize: 23 },
  run: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderColor: palette.line,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 12,
    minHeight: 88,
    padding: 16,
  },
  runCopy: { flex: 1, minWidth: 0 },
  runHeading: { alignItems: "center", flexDirection: "row", gap: 10 },
  runId: {
    color: palette.textMuted,
    fontFamily: "Courier",
    fontSize: 9,
    marginTop: 6,
    maxWidth: 130,
  },
  runMeta: { color: palette.textMuted, fontSize: 10, marginTop: 8 },
  runTitle: {
    color: palette.textPrimary,
    flexShrink: 1,
    fontSize: 16,
    fontWeight: "700",
  },
  statusDot: { borderRadius: 6, height: 12, width: 12 },
  time: { color: palette.textSecondary, fontSize: 12, fontWeight: "600" },
  timeBlock: { alignItems: "flex-end", maxWidth: 140 },
});
