import { StyleSheet } from "react-native";
import { palette } from "../theme";

export const styles = StyleSheet.create({
  canvas: { backgroundColor: palette.canvas, flex: 1, overflow: "hidden" },
  documentTitle: {
    color: palette.textPrimary,
    fontSize: 14,
    fontWeight: "700",
    marginTop: 3,
  },
  editor: { flex: 1, flexDirection: "row" },
  eyebrow: {
    color: palette.textMuted,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 1.1,
  },
  historyButton: {
    alignItems: "center",
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  historyButtonDisabled: { opacity: 0.3 },
  historyButtonText: { color: palette.textSecondary, fontSize: 16 },
  inspector: {
    backgroundColor: palette.surfaceQuiet,
    borderLeftColor: palette.line,
    borderLeftWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 14,
    width: 210,
  },
  inspectorTitle: {
    color: palette.textPrimary,
    fontSize: 14,
    fontWeight: "700",
    paddingVertical: 13,
  },
  instrumentLabel: { color: palette.textSecondary, fontSize: 10 },
  instrumentRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 11,
  },
  instrumentValue: {
    color: palette.textPrimary,
    fontSize: 10,
    fontVariant: ["tabular-nums"],
  },
  layerLabel: { color: palette.textSecondary, flex: 1, fontSize: 10 },
  layerRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 7,
    height: 31,
  },
  layerSelected: { backgroundColor: palette.focusQuiet },
  layerSymbol: { color: palette.textMuted, fontSize: 10, width: 13 },
  layers: {
    backgroundColor: palette.surfaceQuiet,
    borderRightColor: palette.line,
    borderRightWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 7,
    width: 166,
  },
  nativeCanvas: { flex: 1 },
  panelHeader: {
    alignItems: "center",
    borderBottomColor: palette.line,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    height: 43,
    justifyContent: "space-between",
  },
  panelLabel: {
    color: palette.textMuted,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 1,
  },
  panelMeta: { color: palette.textMuted, fontSize: 8 },
  pressed: { opacity: 0.55 },
  preview: {
    color: palette.success,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 1,
  },
  propertyGroup: {
    borderTopColor: palette.line,
    borderTopWidth: StyleSheet.hairlineWidth,
    paddingVertical: 14,
  },
  propertyHeading: {
    color: palette.textMuted,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 1,
  },
  propertyLabel: { color: palette.textMuted, fontSize: 9 },
  propertyRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  propertyValue: {
    backgroundColor: palette.surface,
    color: palette.textPrimary,
    flex: 1,
    fontSize: 10,
    paddingHorizontal: 7,
    paddingVertical: 6,
  },
  root: { backgroundColor: palette.canvas, flex: 1 },
  saveButton: {
    borderColor: palette.line,
    borderRadius: 4,
    borderWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  saveButtonText: {
    color: palette.textSecondary,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 0.7,
  },
  saveGroup: { alignItems: "center", flexDirection: "row", gap: 9 },
  statusOnline: {
    color: palette.success,
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 0.8,
    marginLeft: "auto",
  },
  statusFailed: { color: palette.danger },
  statusStrip: {
    alignItems: "center",
    borderTopColor: palette.line,
    borderTopWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 22,
    height: 27,
    paddingHorizontal: 12,
  },
  statusText: {
    color: palette.textMuted,
    fontSize: 7,
    fontWeight: "700",
    letterSpacing: 0.8,
  },
  statusVerified: { color: palette.success },
  tool: {
    alignItems: "center",
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  toolbar: {
    alignItems: "center",
    borderBottomColor: palette.line,
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    height: 56,
    justifyContent: "space-between",
    paddingHorizontal: 16,
  },
  toolbarCenter: { alignItems: "center", flexDirection: "row", gap: 10 },
  toolbarRule: {
    backgroundColor: palette.line,
    height: 18,
    width: StyleSheet.hairlineWidth,
  },
  toolbarValue: { color: palette.textSecondary, fontSize: 10 },
  toolRail: {
    alignItems: "center",
    backgroundColor: palette.surfaceQuiet,
    borderRightColor: palette.line,
    borderRightWidth: StyleSheet.hairlineWidth,
    paddingTop: 8,
    width: 48,
  },
  toolSelected: { backgroundColor: palette.focusQuiet },
  toolSymbol: { color: palette.textMuted, fontSize: 16 },
  toolSymbolSelected: { color: palette.focus },
  zoom: {
    color: palette.textPrimary,
    fontSize: 10,
    fontVariant: ["tabular-nums"],
  },
});
