import { StyleSheet } from "react-native";
import { palette } from "../theme";

export const styles = StyleSheet.create({
  brand: { color: palette.textPrimary, fontSize: 20, fontWeight: "700" },
  brandDetail: {
    color: palette.textMuted,
    fontSize: 8,
    fontWeight: "800",
    letterSpacing: 1.3,
    marginTop: 2,
  },
  brandRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    minHeight: 48,
  },
  closeButton: {
    alignItems: "center",
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  closeLabel: { color: palette.textSecondary, fontSize: 27, lineHeight: 30 },
  disabledRow: { opacity: 0.45 },
  empty: { color: palette.textMuted, fontSize: 13, padding: 12 },
  newChat: {
    alignItems: "center",
    backgroundColor: palette.surface,
    borderColor: palette.line,
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    marginTop: 6,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  newChatLabel: { color: palette.textPrimary, fontSize: 13, fontWeight: "700" },
  newChatPressed: { opacity: 0.8 },
  newChatSymbol: { color: palette.focus, fontSize: 18, lineHeight: 18 },
  pressedRow: { opacity: 0.62 },
  projectDetail: { color: palette.textMuted, fontSize: 11, marginTop: 3 },
  projectLabel: { color: palette.textPrimary, fontSize: 14, fontWeight: "600" },
  projectCopy: { flex: 1 },
  projectMark: {
    alignItems: "center",
    backgroundColor: palette.focus,
    borderRadius: 10,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  projectMarkText: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
  projectRow: {
    alignItems: "center",
    backgroundColor: palette.surfaceQuiet,
    borderColor: palette.line,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 10,
    marginBottom: 4,
    paddingHorizontal: 11,
    paddingVertical: 11,
  },
  row: {
    borderRadius: 12,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  rowDetail: { color: palette.textMuted, fontSize: 11, marginTop: 3 },
  rowLabel: { color: palette.textPrimary, fontSize: 14, fontWeight: "600" },
  safe: { backgroundColor: palette.sidebar, flex: 1, paddingHorizontal: 12 },
  sectionLabel: {
    color: palette.textMuted,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 1.1,
    marginBottom: 5,
    marginTop: 12,
    paddingHorizontal: 12,
  },
  selectedRow: { backgroundColor: palette.surface },
  serverUrl: { color: palette.textMuted, fontSize: 9, marginTop: 5 },
  session: {
    borderTopColor: palette.line,
    borderTopWidth: StyleSheet.hairlineWidth,
    padding: 12,
  },
  sessionDetail: { color: palette.textSecondary, fontSize: 11, marginTop: 5 },
  sessionTitle: { color: palette.textPrimary, fontSize: 12, fontWeight: "600" },
  statusDot: { borderRadius: 4, height: 7, width: 7 },
  statusRow: { alignItems: "center", flexDirection: "row", gap: 7 },
  threads: { flex: 1 },
});
