export const expectedHeadings = [
  "Dossier metadata",
  "Identity and pinned snapshot",
  "Provenance and license",
  "Repository and package map",
  "Executable entrypoints",
  "Control and data flow",
  "Module and extension boundaries",
  "Agent interface",
  "Tool interface",
  "Provider interface",
  "Model interface",
  "Context interface",
  "State, persistence, and restart",
  "Concurrency, worktree, and isolation",
  "Permissions, authority, and sandbox",
  "Evidence and observability",
  "Resource, token, and cost accounting",
  "Failure, cancellation, and retry",
  "Install, update, and release",
  "Tests and qualification",
  "Security",
  "Strengths",
  "Liabilities",
  "Transferable patterns",
  "Rejected patterns / CURIOSITY_NO_GO",
  "Adversarial probes",
  "Claims register",
  "Source ledger",
  "Normalized summary record",
  "Uncertainties and follow-ups",
];

export const expectedDimensions = [
  "identity_snapshot",
  "provenance_license",
  "repository_package_map",
  "executable_entrypoints",
  "control_data_flow",
  "module_extension_boundaries",
  "agent_interface",
  "tool_interface",
  "provider_interface",
  "model_interface",
  "context_interface",
  "state_persistence_restart",
  "concurrency_worktree_isolation",
  "permissions_authority_sandbox",
  "evidence_observability",
  "resource_token_cost_accounting",
  "failure_cancellation_retry",
  "install_update_release",
  "tests_qualification",
  "security",
  "strengths",
  "liabilities",
  "transferable_patterns",
  "rejected_patterns_curiosity_no_go",
];

export const requiredSourceFields = [
  "source_id",
  "source_kind",
  "title",
  "url",
  "commit_or_ref",
  "resolved_commit",
  "package_identity",
  "code_path",
  "symbol",
  "line_anchor",
  "command",
  "command_environment",
  "output_or_hash",
  "access_date",
  "supports_claims",
  "notes",
];
