export const TUI_DESIGN_TOKENS = Object.freeze({
  color: Object.freeze({
    accentDim: "#3E6C82",
    activity: "#8BD5F7",
    canvas: "#07090B",
    code: "#A7CFB2",
    danger: "#E8847E",
    focus: "#8BD5F7",
    line: "#1B242A",
    lineStrong: "#2A353C",
    plugin: "#B7A6E8",
    success: "#82C7A5",
    surface: "#0E1418",
    surfaceQuiet: "#0A0F12",
    textMuted: "#64727A",
    textPrimary: "#E7EDF0",
    textSecondary: "#9AA8AF",
    warning: "#D7B873",
  }),
  lightColor: Object.freeze({
    accentDim: "#3D6B35",
    activity: "#176B00",
    canvas: "#FFFFFF",
    code: "#2D6D40",
    danger: "#B42F32",
    focus: "#176B00",
    line: "#AEB8BD",
    lineStrong: "#7D898F",
    plugin: "#6C4BB3",
    success: "#22734F",
    surface: "#FFFFFF",
    surfaceQuiet: "#FFFFFF",
    textMuted: "#5D686E",
    textPrimary: "#171A1C",
    textSecondary: "#3F4B51",
    warning: "#815E00",
  }),
  glyph: Object.freeze({
    applied: "✓",
    authored: "◇",
    healthy: "●",
    held: "▲",
    plugin: "◆",
    proposed: "○",
    rail: "│",
    railEnd: "╵",
    railStart: "╷",
    refuted: "✗",
    rule: "─",
    ruleLead: "╶",
    running: "◐",
    unresolved: "▮",
  }),
  layout: Object.freeze({
    compactColumns: 80,
    compactRows: 30,
    contentInset: 2,
    idleComposerWidth: 76,
    inspectorMinColumns: 104,
    inspectorWidth: 38,
    paletteWidth: 78,
    readingWidth: 112,
    responseInset: 3,
  }),
  motion: Object.freeze({
    activeFrameMs: 120,
    idleAnimation: false,
  }),
});

export type TuiDesignTokens = typeof TUI_DESIGN_TOKENS;
